### ISSUE TITLE
access to single Github accounts

### ISSUE THREAD

**Issue by parkin** [benbalter/jekyll-auth#100]
Could you add the ability to authenticate against a list of individual Github accounts? Right now, to give myself access, I need to create a new organization with me as the only member and give that organization access. Instead, it would be nice to be able to authenticate against my personal Github account, and maybe additionally a list of Github accounts.

**Comment by benbalter** [comment]
If anyone is interested in implementing this, I'd be glad to help/review a pull request that adds this functionality.
