### ISSUE TITLE
Deployment using Unicorn and Nginx

### ISSUE THREAD

**Issue by fossejc** [benbalter/jekyll-auth#102]
Hi guys,

I am new to Ruby but I was able to develop locally a jekyll website using jekyll auth. 
Now I would like to deploy it on a debian jessie 8 VPS using `unicorn` and `nginx`. I am able to make it work locally using `jekyll-auth` command or `unicorn` command. However, as soon as I launch it using `bundle exec unicorn -c unicorn.rb -E production` and nginx my browser issues multiple requests. Then github tells me that I need to give back the authorisation as the application sent too many requests. Any ideas on want could be wrong ? If needed I can add my unicorn and nginx configuration. 
The callback url is set as follow `http://192.168.64.16/auth/github/callback`. Does it need be https ?
Thanks for your help ! 

If I am able to deploy it I would love to share my setup.

**Comment by benbalter** [comment]
@fossejc I don't have experience with what you're describing, but it should be possible. A quick Google search revealed http://recipes.sinatrarb.com/p/deployment/nginx_proxied_to_unicorn, which may help (Jekyll Auth is based on Sinatra).
