### ISSUE TITLE
Returning "Not Found"

### ISSUE THREAD

**Issue by madblkman** [benbalter/jekyll-auth#106]
I've been integrating MkDocs and Jekyll-auth. Everything seems to be working, as far as the authentication, but once it's time to show the actually page it returns "Not Found".  The logs aren't telling me much.  Looks like the server is trying to get "/" but coming up empty handed. Any ideas on what I could be doing wrong?

**Comment by glampr** [comment]
I'm having a similar issue.
For me, the pre-compilation of the assets created the .html pages for all .md pages in the project's root folder, but all other .md pages in subfolders, were NOT compiled to their .html equivalents.
Does the compilation only happen in the root folder?
Is there a config option that needs to be toggled so that it traverses the rest of the subfolders?

**Comment by benbalter** [comment]
> in the project's root folder

Per https://github.com/benbalter/jekyll-auth/pull/90 the static files must be in `/_site` (Jekyll's default build location). If anyone is interested in picking up where #90 left off, that could be configurable (which I believe is the issue here).

**Comment by glampr** [comment]
My sites files are compiled in ```/_site```.
But only the one's that are in the root folder.

E.g.
```
+ root
    index.md
    about.md
  + subproject1
      index.md
      stats.md
```

Top level files index.md and about.md get compiled to .html, but the files inside subproject1 are not compiled, inside the ```/_site/subproject1``` folder only the .md files are copied over, but there are no .html files there.
Any ideas?

**Comment by madblkman** [comment]
So I've been using the `source` option in the `_config.yml` file which allows me to build the MkDocs `site` folder to serve to Jekyll. So currently my folder looks like this:

` + root`
`- + _site`
`-- + css`
`-- + fonts`
`-- + img`
`-- + js`
`-- + mkdocs`
`-- 404.html`
`-- index.html`
`-- search.html`
`-- sitemap.xml`

According to the code in JekyllAuth::JekyllSite (how it's currently assembled) it should generate the site. But even after I implemented some of the changes from #90 I still come up with a 404. At first I thought it was the Jekyll server but it doesn't seem like it is since the page generates fine locally minus the authentication. I'm starting to wonder if MkDocs just doesn't play nice with Jekyll-auth at this point.

**Comment by benbalter** [comment]
>  I'm starting to wonder if MkDocs just doesn't play nice with Jekyll-auth at this point.

I'm not familiar with MkDocs, but theoretically, if you set the site's source to MkDoc's compiled output, Jekyll should just copy it from `source` to `_site` and then serve any HTML files in the `_site` folder. One potential way to debug would be to navigate to the `_site` folder while the serve is running, examine its contents, and potentially manually add a file to confirm it's served.

**Comment by madblkman** [comment]
I figured it out!

So apparently I was missing a `Procfile`. Once I set that up with `web: bundle exec jekyll-auth serve --port $PORT --host 0.0.0.0` everything worked as it should. If it's cool, I would like to submit a pull request to add that as a troubleshooting method if you're cool with it.
