### ISSUE TITLE
Not Found

### ISSUE THREAD

**Issue by mikederksen** [benbalter/jekyll-auth#107]
Hello there,

I have followed the instructions to setup a heroku website with the desired files. Authentication works fine, but the index file is not presented. When the user is authenticated, a 'Not Found' message is displayed. It seems that the website is listening to the root folder of the repository, instead of the generated '_site' directory. How can i change this behaviour?

When i run a 'ls' command from the heroku console, I can see that the '_site' folder is generated and that it contains a index.html file.

Thanks!

**Comment by benbalter** [comment]
Perhaps https://github.com/benbalter/jekyll-auth/blob/master/lib/jekyll_auth/jekyll_site.rb#L4 may be the cause? We could base it relative to the file, in the event the working directory is not the same as the site root.
