### ISSUE TITLE
Are multiple teams supported?

### ISSUE THREAD

**Issue by argenos** [benbalter/jekyll-auth#123]
After giving up for a while, I finally managed to get one of our projects running on Heroku. Specifying the `GITHUB_ORG_NAME` always resulted in the bouncer, but once a `GITHUB_TEAM_ID` was specified, we could access the site. This raises the question in the title, are multiple teams supported?

**Comment by zacksinclair** [comment]
I am also wondering if this supports multiple teams or multiple orgs?
