### ISSUE TITLE
Gets denied always

### ISSUE THREAD

**Issue by prolike** [benbalter/jekyll-auth#141]
### Everyone in the organization gets denied

I have an organization with the Oauth app, and the repository is on one of the members account.
But all the members are getting denied.
Is it because the repository has to be owned by the organization?
And does it have to be private?

**Comment by wonderbird** [comment]
Hi @benbalter and @prolike ,

maybe I have encountered the same issue. After following the [Getting Started](https://github.com/benbalter/jekyll-auth/blob/master/docs/getting-started.md) guide, I ended up with my sample Jekyll page showing the error 403 access denied cat.

Please consider adding the following steps to the documentation. They fixed the problem on my side:

1. Add a team to your organization containing the members who should have access and configure the GITHUB_TEAM_ID for heroku
2. Grant OAuth App access to your Jekyll App in your organization

## Detailed step descriptions

### 1. Add a team to your organization containing the members who should have access and configure the GITHUB_TEAM_ID for heroku

* Create a team within your organisation
* Create a REST API token for your lokal heroku / jekyll installation
* Save the REST API token by adding the line `GITHUB_TOKEN=<your token>` to `.env` (never commit that!)
* Find out your numeric team id by `jekyll-auth team_id --org <your org name> --team <your team name>`
* Tell heroku your team id by `heroku config:set GITHUB_TEAM_ID=<your numeric team id>`

### 2. Grant OAuth App access to your Jekyll App in your organization

* After the team id was provided to the application, it showed an **error 500**.
* Checking the logs on heroku revealed the message <br>`2021-06-29T03:44:45.449035+00:00 app[web.1]: 2021-06-29 03:44:45 - Octokit::Forbidden - GET https://api.github.com/teams/4923947/members/wonderbird: 403 - Although you appear to have the correct authorization credentials, the `boos-systems` organization has enabled OAuth App access restrictions, meaning that data access to third-parties is limited. For more information on these restrictions, including how to enable this app, visit https://docs.github.com/articles/restricting-access-to-your-organization-s-data/ // See: https://docs.github.com/rest:`
* [Approving OAuth Apps for your organization](https://docs.github.com/en/organizations/restricting-access-to-your-organizations-data/approving-oauth-apps-for-your-organization) made the page work. You have to select your heroku application and grant access.
