### ISSUE TITLE
Will this work with Netlify?

### ISSUE THREAD

**Issue by mckeever02** [benbalter/jekyll-auth#149]
More a question than feature request. Will this work with Netlify hosting? Currently, password-protected sites using netlify requires a paid account so I'm looking around for alternative ways to do it.

Thanks

**Comment by alexsayal** [comment]
Hi @mckeever02! Just wondering if you found a way to do this using netfly or any other service other than Heroku.

Thanks!

**Comment by mckeever02** [comment]
@alexsayal I didn't unfortunately. I ended up having to switch gears and implement auth on the client side using [Firebase auth](https://firebase.google.com/docs/auth).

**Comment by benbalter** [comment]
This would not work with Netlify, but based on https://docs.netlify.com/visitor-access/identity/, it should be possible to implement a similar functionality within Netlify's configuration.
