### ISSUE TITLE
jekyll-auth not working on heroku webapp leveraging github org account 

### ISSUE THREAD

**Issue by equalsJeffH** [benbalter/jekyll-auth#29]
Ok, so AFAICT, I got jekyll-auth integrated into a ruby-based site that I've instantiated on heroku, and registered the app at `https://github.com/settings/applications`. Everything now gets setup without errors.

And...even if I am not logged-in to github.com, i have full access to the site :(

I also tried running the site locally via jekyll-auth, and experienced the same results.

all the site does is serve files in the site's root directory if they are explicitly named on the URL. 

Any hints on what to do in order to figure out what's going on?

thanks!

**Comment by fkostadinov** [comment]
You might want to try these things:

1. Make sure you haven't accidentally whitelisted everything.

2. Often, as a developer you are also the owner of the GitHub repository. The owner automatically has admin access to every repository in the organization. To test whether authorization works correctly, you must set up a team that has access to only the targeted repository and a user that is not an owner (or a member) but only in that team. But before you test anything, make sure you delete all browser cookies and then shut down the browser before trying again.

**Comment by estiens** [comment]
I have the same issues. Despite setting up jekyll-auth with the appropriate ENV variables, I can run `jekyll-auth serve` locally and see the full site, and on heroku I see the full site as well. Nothing is whitelisted.

**Comment by estiens** [comment]
NB: I figured out that if you already have a `config.ru` file it won't update it. You need to delete your `config.ru`file and generate a new one with jekyll-auth new or create a new file with the following lines: ```require "jekyll-auth"
run JekyllAuth.site```
