### ISSUE TITLE
GITHUB_ORG_ID fails, GITHUB_TEAM_ID works...

### ISSUE THREAD

**Issue by jasonm23** [benbalter/jekyll-auth#32]
Tried to authenticate an organisation, jekyll-auth failed to allow entry.

Used a team id instead, worked fine.

Low priority for me, as I setup a new team and added all org members to it.

**Comment by benbalter** [comment]
I believe this should now be fixed (that logic has been rewritten and now has tests associated with it). Please let me know if that's not the case.
