### ISSUE TITLE
jekyll-auth new fails at first step

### ISSUE THREAD

**Issue by vallettea** [benbalter/jekyll-auth#38]
Hello,

after `jekyll-auth new` I get:

```
Would you like to set up Heroku now? (Y/n)
yes
error: undefined method `[]' for nil:NilClass. Use --trace to view backtrace
```

same if I press yes

**Comment by benbalter** [comment]
The `new` command has been completely rewritten, and now has tests to ensure it works going forward. Sorry for the hassle @vallettea and thanks for the feedback. This should be fixed on `master` now, and in the next release.

**Comment by vallettea** [comment]
:+1:
