### ISSUE TITLE
Access Denied Problem

### ISSUE THREAD

**Issue by fkostadinov** [benbalter/jekyll-auth#40]
No matter what I do I cannot get past the login screen. All I ever receive after login to the hosted website is a HTTP 403 and the image of the bouncer.

Here's my setup:
1. My organization is _foo-org_. There is a team _bar-team_ and a private repo _baz-repo_.
2. I am both owner and member of foo-org, and also team member of _bar-team_.
3. I grant write access to all members in _bar-team_. (Organisation owners have admin rights anyway.)
4. I make sure that _bar-team_ is listed under the repo's list of collaborators. (Organisation owners and members are listed there too. Organisation members have write access.)
5. Inside Heroku's dashboard there is my Heroku app with the config vars. Besides the other vars there is a var "GITHUB_TEAM_ID" and I set the value to "@foo-org/bar-team" (without double quotes but with the leading at character).
6. I have completely deleted the "whitelist" entry (also the "ssl" entry) from _&#95;config.yml_. (When I whitelist everything, then I can indeed access the website. But of course it's not protected then. Still this demonstrates that everything seems to be set up right.)
7. Before every new attempt, I deliberately delete all cookies in my browser. I also tried to revoke granted access rights in GitHub to no avail.

Still, access is not granted. Heroku's logs do not say very much. The app is up and running without errors. It looks like the callback works fine between Heroku and GitHub. However, I can see that all HTTP GETs to any file on the protected website results in a 403 access denied.

Now I am out of ideas. Could there be something wrong with the org/team id? Any help is appreciated.

**Comment by antn** [comment]
Hey there,

I think the problem you're running into is with your GITHUB_TEAM_ID. As seen in the [readme](https://github.com/benbalter/jekyll-auth#with-authentication), this value should be a number, and not in the @foo/bar format. As for getting this number, I'm not sure the best way to actually get it. I do know that you can get a list of teams that includes their IDs with the [GitHub API](https://developer.github.com/v3/orgs/teams/#list-teams), so hopefully that can work for you (I don't see anywhere in the actual site that displays a team ID, but if there is a way, I'd love to know how to do it!). Hopefully that gets everything working for you!

**Comment by fkostadinov** [comment]
Thanks, antn, that effectively did the trick! I effectively needed to set GITHUB_TEAM_ID to a numeric id value, after that everything worked. From the README alone I could never have found out.

To find a team's id:

1. Make sure you have cURL installed.
2. Make sure you are a member of the team for which you want to find the ID.
3. In your personal account settings, go to applications. Then click _Generate New Token_ under _Personal Access Tokens_.
4. Make sure you select _read:org_. Give your token a name.
5. Open a shell. Type: _curl -i -H "Authorization: token <very-long-auth-token-string>" https://api.github.com/orgs/<org-name>/teams_. Replace &lt;very-long-auth-token-string> with your authorization token and &lt;org-name> with the organization's name this team belongs to. In a Windows shell, you must use double quotes ("), but if you're running Unix/Linux maybe you'll have to use single quotes ('). Can't say.
6. You will receive JSON including all teams for the given organization including the ID for each team. In my case its simply a six or seven digit integer (e.g. 1234567). Now set your GITHUB_TEAM_ID to this value.

**Comment by benbalter** [comment]
Thanks for writing this up @fkostadinov. Hope to add a command-line interface to simplify the process, as it's a problem I run into myself (https://github.com/benbalter/jekyll-auth/issues/41). If there are any changes that we can make to the documentation to make things clearer, would love a pull request.
