### ISSUE TITLE
Consistent naming

### ISSUE THREAD

**Issue by benbalter** [benbalter/jekyll-auth#48]
Right now, Jekyll auth is `jekyll-auth` but from what I'm reading [it should be `jekyll_auth`](https://stackoverflow.com/questions/4687659/should-one-use-dashes-or-underscores-when-naming-a-gem-with-more-than-one-word). I made things consistent internally, but the gem name is still unchanged. 

Is it worth changing? @parkr would :heart: your thoughts.

**Comment by parkr** [comment]
I don't think so – it really only makes a big difference if you're trying to integrate with some kind of auto-loading mechanism (e.g. the one in Rails) which determines the filename based on a class name. So I think you're good here. 👍
