### ISSUE TITLE
jekyll-auth 1.0.1 | Error:  uninitialized constant JekyllAuth::Comands

### ISSUE THREAD

**Issue by pmackay** [benbalter/jekyll-auth#53]
Am trying to run the `jekyll-auth` command and getting this error:

`jekyll-auth 1.0.1 | Error:  uninitialized constant JekyllAuth::Comands`

Any suggestions how I can resolve it?

**Comment by benbalter** [comment]
I believe `1.0.2` should resolve the issue: https://github.com/benbalter/jekyll-auth/releases/tag/v1.0.2
