### ISSUE TITLE
Cannot get org ID from CLI

### ISSUE THREAD

**Issue by estiens** [benbalter/jekyll-auth#57]
Tried to get org (or team) ID from CLI using example, get the following response. Had to use Github API to get my team ID.

```jekyll-auth team_id --org jekyll --team maintainers
No WARDEN_GITHUB_VERIFIER_SECRET environmental variable found.
Your sessions are likely being stored insecurely.
invalid option: --org```

**Comment by benbalter** [comment]
> `invalid option: --org`

There is a warning that could be ignored regarding Warden, an an error. The argument should be `org_name`.
