### ISSUE TITLE
Add how to set up application with callbacks, etc. to Readme

### ISSUE THREAD

**Issue by benbalter** [benbalter/jekyll-auth#6]
e.g., `http://[domain]/auth/github/callback`

props @jglovier for spotting the problem.

**Comment by bbarker** [comment]
I actually don't see this in the README.md. Additionally, I don't know what to put into the callback url field **and** the homepage URL field while filling out the github application form, since I'm totally unfamiliar with Heroku (though I am a bit familiar with working on OAuth).

Thanks!

**Comment by bbarker** [comment]
To elaborate a bit, I think step 3 under *Create a GitHub Application* could be clarified for new Heroku users, and an additional step for specifying the callback URL could be given for new Heroku users.

Presumably domain would be 'horoku.com' or some other domain given to you by Heroku?

**Comment by bbarker** [comment]
I think I figured it out, but please see #59.
