### ISSUE TITLE
Possible issue with automated method for installation?

### ISSUE THREAD

**Issue by bbarker** [benbalter/jekyll-auth#61]
I have successfully finished an installation using the manual method, which may be what I wanted anyway since I'm using an orphan branch of github rather than a new repo. However,  I started out with trying the automated procedure and recalled I had some error to the effect of my command being invalid (sorry I don't remember the exact error, and I don't want to try again as I already have the site working and really don't know much about what I'm doing), e.g.:

```
bundle exec jekyll-auth --client_id XXX --client_secret XXX --team_id XXX
```

Please ignore this nearly useless issue if it is working, just wanted to throw out the possibility there is a typo or something.

**Comment by benbalter** [comment]
Marking as closed unless others can reproduce. Thanks @bbarker for the report.
