### ISSUE TITLE
Selectively require organization access?

### ISSUE THREAD

**Issue by coryfklein** [benbalter/jekyll-auth#65]
When users visit a GitHub Pages site that uses jekyll-auth, it asks for permission to access their GitHub Organizations. However, it isn't limited to just the organization associated to the GitHub Pages site, but it requests access to *all* of their organizations. This makes some of my associates rather uncomfortable.

![image](https://cloud.githubusercontent.com/assets/3503322/7848474/460c7ac8-0489-11e5-999f-0611076a16f1.png)

Am I missing a configuration somewhere that will make my instance only require access to the one organization it is associated with?

**Comment by benbalter** [comment]
This currently isn't possible via the GitHub API. You cannot scope an API request to only one organization from the client. Each organization can activate app restrictions from their side, which would have the same affect unless authorized by an admin.
