### ISSUE TITLE
Passing build options to jekyll-auth

### ISSUE THREAD

**Issue by pputzky** [benbalter/jekyll-auth#67]
Hi Ben & thanks for the great package!

I am trying to pass additional options to jekyll-auth during the build process. However, it is not really clear to me of how to do that. If I try to pass e.g. --watch I receive the following

    $ bundle exec jekyll-auth build --watch
    jekyll-auth 1.0.3 | Error:  Whoops, we can't understand your command.
    jekyll-auth 1.0.3 | Error:  invalid option: --watch
    jekyll-auth 1.0.3 | Error:  Run your command again with the --help switch to see available options.

As I understand the syntax to run jekyll-auth is 
```
    jekyll-auth <command> options
```    

So I assumed options would be arguments that will be passed unchanged to *jekyll build* such that
```
    jekyll-auth build options
```
results in 
```
    jekyll build options
```

What am I missing here?

**Comment by jsnlam** [comment]
Similarly, I'm trying to pass in --drafts and got the same error. Looks like mercenary is doing some validation on options.

**Comment by benbalter** [comment]
I don't believe this behavior is currently supported, but it would be great if it was. Glad to merge a pull request if anyone wants to tackle this. For `--watch`, I'd just use `jekyll serve --watch`.

**Comment by jsnlam** [comment]
One quick fix is to expose the same options available in jekyll (lib/jekyll/command.rb) to bin/jekyll-auth, e.g. under the 'build' command - 
```ruby 
c.option 'show_drafts',  '-D', '--drafts', 'Render posts in the _drafts folder'
```
But there is probably a better way?

**Comment by benbalter** [comment]
Generally, I'd recommend using jekyll-auth locally to confirm authentication works, but otherwise using Jekyll serve for locally development (which should still work).
