### ISSUE TITLE
What should the first page look like by default?

### ISSUE THREAD

**Issue by pratik60** [benbalter/jekyll-auth#68]
![screen shot 2015-08-22 at 3 13 07 pm](https://cloud.githubusercontent.com/assets/2249430/9423421/8bedf4a4-48e0-11e5-92ba-d1620bcb5e82.png)

This is what it looks like right after I've spun up something new....Is this intentional or not?

Shouldn't the first page contain an already filled out read-me, with basic markdown, toc and all...Should I first set up jekyll before I set up this. Not really sure what to do now?

**Comment by benbalter** [comment]
Without an index.html (or index.md file + front matter), by default, the Gem should show exactly what you've displayed. The Gem is intended to be added to an *existing* or *new* Jekyll site, and creates no output of its own, other than the access denied page.
