### ISSUE TITLE
Missing step? Everything works except for the secured content

### ISSUE THREAD

**Issue by jarrodparkes** [benbalter/jekyll-auth#70]
I finally have everything running at https://udacity-meta-test.herokuapp.com/. By default everything is whitelisted except for...

<pre>
jekyll_auth:
  whitelist:
    - "^((?!secure).)*$"
</pre>

When I visit https://udacity-meta-test.herokuapp.com/secure or https://udacity-meta-test.herokuapp.com/secure/secure.html I am correctly redirected to the Github OAuth; however, upon authorizing the app, I am redirected to the page with the bouncer cat :cry: !

My thought is that something is configured incorrectly on Heroku's side? I've checked the config variables on Heroku and `GITHUB_CLIENT_ID`, `GITHUB_CLIENT_SECRET`, and `GITHUB_ORG_ID` all look correct.

I also added a `JEKYLL_GITHUB_TOKEN ` to Heroku's config variables which is an access token from my Github account to silence the `Jekyll.logger.warn "GitHubMetadata:", "No GitHub API authentication could be found." +
           " Some fields may be missing or have incorrect data."` that was being raised by `bundle exec jekyll-auth build`.

Any thoughts on why I'm still having this issue?

**Comment by benbalter** [comment]
Is the app a personal app or an organization app?

**Comment by jarrodparkes** [comment]
It is a personal app currently. And it appears (after looking at the logs) that it is trying to hit a GITHUB_TEAM_ID instead of a GITHUB_ORG_ID.

`2015-09-03T03:43:32.503224+00:00 app[web.1]: I, [2015-09-03T03:43:32.503112 #3]  INFO -- : Authentication strategy: team`

So you may have just answered my question :+1:

**Comment by jarrodparkes** [comment]
@benbalter I've switched over to an organization app, but it turns out I'm still having the same issue. Everything works except for the secure content.

I'm seeing this in the logs each time I request the secure page:

`2015-09-03T21:27:24.342771+00:00 app[web.1]: I, [2015-09-03T21:27:24.342657 #3]  INFO -- : Authentication strategy: org`

`2015-09-03T21:27:26.421838+00:00 heroku[router]: at=info method=GET path="/secure.html" host=udacity-meta.herokuapp.com request_id=504e7f92-c52e-4eb2-a5e0-08f5a5822e2c fwd="162.17.79.97" dyno=web.1 connect=1ms service=37ms status=403 bytes=453`

**Comment by jarrodparkes** [comment]
@benbalter 

I found the issue! The problem is that Sinatra is looking for the **organization name** and not the organization id (although the team check is for id). You can see that here in the code...

<pre>
#
# name - the organization to test membership against
#
# Returns an execution halt if the user is not a member of the named org
def github_organization_authenticate!(name)
  authenticate!
  halt([401, "Unauthorized User"]) unless github_organization_access?(name)
end
</pre>

**Comment by jarrodparkes** [comment]
I'd love to try and help contribute by making this fix (it would actually be my first true open source contribution), either in the documentation (quick fix) or to adjust things to use ORG_NAME instead of ORG_ID. Thoughts? Recommendations?

**Comment by jarrodparkes** [comment]
@benbalter 

I made a PR with the fix.

**Comment by benbalter** [comment]
Thanks again @jarrodparkes!
