### ISSUE TITLE
Limit to certain people in the org?

### ISSUE THREAD

**Issue by gleehokie** [benbalter/jekyll-auth#74]
Is it possible to configure jekyll-auth to restrict access to a list of users or only the users that have access to the GitHub project instead of the organization?

**Comment by parkr** [comment]
You could do team membership as well via Octokit. Not built-in though.

**Comment by benbalter** [comment]
> Is it possible to configure jekyll-auth to restrict access to a list of users or only the users that have access to the GitHub project instead of the organization?

Yes. set `GITHUB_TEAM_ID` rather than `GITHUB_ORG_NAME` to limit access to a specific team within the organization.
