### ISSUE TITLE
Finer-grained authorization (and maybe page-based access control?)

### ISSUE THREAD

**Issue by patmaddox** [benbalter/jekyll-auth#76]
Hi, I'd like to use this to do more fine-grained authorization with multiple teams. For example, people in team1 should get access to a certain set of pages, and people in team2 should get access to a different set of pages. So it's not quite as simple as allowing a team or set of teams.

Additionally, I'm interested in defining the access control within pages, rather than the whitelist approach. So in my jekyll front-matter I might have something like:

```
# jekyll front matter
jekyll_auth_teams: team1, team2 # maybe this needs to be numbers, I don't know
```

Since the pages are pre-built, I think this would need to generate a file that gets committed & pushed, and then loaded dynamically.

My questions:
1. Does this plugin accept the kind of finer-grained access control that I talked about? (I don't think so?)
2. Would you consider adding it / accepting pull requests to implement it?
3. What's your take on specifying access control via jekyll front matter? Do you think it's feasible? Do you have ideas for a different approach?

Thanks,
Pat

**Comment by benbalter** [comment]
> Would you consider adding it / accepting pull requests to implement it?

Of course! I think that's a great idea (even if I don't personally have a need for it).

> What's your take on specifying access control via jekyll front matter? Do you think it's feasible? Do you have ideas for a different approach?

It depends on the implementation, but I think that makes sense and is a good/logical design pattern.
