### ISSUE TITLE
Cookies are not being deleted

### ISSUE THREAD

**Issue by FlaviaFortes** [benbalter/jekyll-auth#81]
I'm not sure this is an issue, but, if anyone could light things up for me a bit I would appreciate it.

I have a Jekyll site. I followed all the steps on jekyll-auth README and it's working fine. 
The problem is:
When I log into my site with a valid github account I can access the site, but if I log out, I continue accessing my Jekyll site because the cookies are saved. The other way around also occurs: When I access my Jekyll site with an invalid github account I get the bouncer response, but if on another tab I log in with a valid github account I still can't access.

Is there any config I'm missing? Or a workaround?

If this is not the proper place for this discussion I would be happy to move it.

**Comment by benbalter** [comment]
> but if I log out, I 

How are you trying to log out?

**Comment by FlaviaFortes** [comment]
I'm logging out through another tab.

**Comment by FlaviaFortes** [comment]
On the github site, not mine.

**Comment by benbalter** [comment]
Try using the `/logout` route on your site, that may do it.

**Comment by FlaviaFortes** [comment]
Nothing happens. The cookies are still there.

**Comment by FlaviaFortes** [comment]
Actually, I think the `/logout` works. But it redirects to `/`, then to the github login again. This creates another session. :)

I believe the behaviour is correct!

**Comment by nicosuave** [comment]
In my eyes, this would be the correct behavior: https://developer.github.com/v3/oauth_authorizations/#delete-a-grant

**Comment by cortix** [comment]
> Actually, I think the `/logout` works. But it redirects to `/`, then to the github login again. This creates another session. :)
> 
> I believe the behaviour is correct!

Although I try `/logout`, I get a similar result with you. Did you find a solution?
