### ISSUE TITLE
authorize google custome search engine

### ISSUE THREAD

**Issue by sklosedr** [benbalter/jekyll-auth#86]
I want to authorize google custome search engine for crawling the heroku app? How can this be configures?

What is your suggestion to enable search functionality for jekyll-auth protected site?

Thanks and best regards
Stefan

**Comment by benbalter** [comment]
What type of authentication can GSA provide?

**Comment by sklosedr** [comment]
We dont need this feature anymore as we dedided not to use Github authentication
