### ISSUE TITLE
authorize also outside-collaborators

### ISSUE THREAD

**Issue by sklosedr** [benbalter/jekyll-auth#87]
Hi,

jekyll auth works fine for organization member, but we need to authorize also outside-collaborators.
How ca we do it?

As an alternative it would be helpful to maintain a list auf github user who are allowed to access

Thanks in advance
Stefan

**Comment by benbalter** [comment]
This is not currently implemented, but would be certainly possible. The necessary change would need to be near https://github.com/benbalter/jekyll-auth/blob/master/lib/jekyll_auth/auth_site.rb#L31. I'd be more than glad to review and help you with a pull request if you're able to submit one.

**Comment by sklosedr** [comment]
We dont need this feature anymore as we dedided not to use Github authentication

**Comment by tovbinm** [comment]
Bummer. I would be happy to have it. I just opened a duplicate #110.
