### ISSUE TITLE
Clean URLs on heroku?

### ISSUE THREAD

**Issue by arthur24b6** [benbalter/jekyll-auth#88]
I've successfully deployed to heroku but have been unable to get clean (ie: no .html extensions) functional. There are a bunch of tutorials on using TryStatic but I haven't had any luck. Any pointers on getting this to work?

**Comment by benbalter** [comment]
The easiest way to get clean URLs would to do it within Jekyll, e.g., set your permalink settings globally and manually set permalinks to e.g., `/about/`, instead of the default `/about.html`.

**Comment by arthur24b6** [comment]
That wasn't working for me unfortunately. I think (and I definitely don't have a full understanding of things here) sinatra has to handle the routing here. I added the following to jekyll_site.rb and was able to get what I was hoping for. Maybe not the right way to do this but was correctly rendering content for `http://mysite.com/path` from `http://mysite.com/path.html` 

```
    # Rewrite calls to .html files if they exist.
    get '/:path' do
      file = File.join(File.expand_path(destination, Dir.pwd), "#{params['path']}.html")
      if File.exists?(file)
        File.read(file)
      else
        not_found
      end
    end
```
