### ISSUE TITLE
is it possible to add GitLab support?

### ISSUE THREAD

**Issue by haochenx** [benbalter/jekyll-auth#91]
What I mean is both gitlab.com and GitLab on private servers. This should not be difficult since GitLab also have OAuth2 support built in, and group information is accessible though API.

**Comment by benbalter** [comment]
Yes, it should be possible, but I don't have much experience with the GitLab API. If there's something similar to https://github.com/atmos/sinatra_auth_github, but for GitLab, it'd certainly be easy. Glad to review a pull request if you're able to start one.

**Comment by haochenx** [comment]
sorry but I'm not familiar with Ruby at all (I'm myself a Java developer). I may try to learn Ruby soon and start a PR for this.

Although written in Go, the oauth2_proxy project is probably a good reference. The related PR that added support for GitLab is https://github.com/bitly/oauth2_proxy/pull/211/files. Although it seems that we need to have a list of users of a specific group. We should be able to obtain the list though the GitLab API, http://docs.gitlab.com/ce/api/groups.html
