### ISSUE TITLE
Using jekyll-auth w/ Heroku PR/review apps

### ISSUE THREAD

**Issue by dtrenz** [benbalter/jekyll-auth#92]
This is a great project, thank you.

I'm having trouble getting a site that I'm using this on to work with Heroku review apps. When I go to the review app URL (e.g. https://my-app-pr-121.herokuapp.com/) I always get the unauthenticated page. I believe this is because the adhoc review app subdomain that includes the PR # is not configured in my GitHub org as an OAuth app URL.

Is there anyway around this?

**Comment by benbalter** [comment]
> Is there anyway around this?

I don't know of any way around this, as the OAuth app needs to know the callback URL. You could implement your own authentication, that's some how passed to the preview app, but if it can't be a subdomain, I'm not sure how the cookies would work.

**Comment by dtrenz** [comment]
I figured this was the case. I'll live ;)

Thanks!
