### ISSUE TITLE
Instructions/link to login to GitHub on the "Access Denied" page

### ISSUE THREAD

**Issue by dtrenz** [benbalter/jekyll-auth#93]
Don't get me wrong, I love the bouncer, but I've had people go to my site and be confused by it. Would it be possible to customize the "Access Denied" page?

Or is it possible to differentiate from logged out vs. unauthorized? Maybe redirect them to github.com/login if they are simply not authenticated?

**Comment by benbalter** [comment]
> Maybe redirect them to github.com/login if they are simply not authenticated?

That should happen. Is it not? 

> Would it be possible to customize the "Access Denied" page?

It looks like we just have to [set `@unathenticated_template](https://github.com/atmos/sinatra_auth_github/blob/master/lib/sinatra/auth/github.rb#L25) to the path to a different template, and it should just work. Perhaps a `401.html` in the repo root?

**Comment by dtrenz** [comment]
It doesn't always redirect. I had to close the browser to trigger that. Also, is a cookie or something used after OAuth? I've noticed that I can sign out of GitHub and go to the website and still access it.

**Comment by mebster** [comment]
@benbalter: you wouldn't happen to have a gist of your "set `@unathenticated_template" trick?  I'm struggling to make it work, and I'm afraid I don't speak Ruby :-S, but love Jekyll :-)

**Comment by benbalter** [comment]
This is probably the simplest way:

```ruby
 class MyBouncer < Sinatra::Base
        enable :raise_errors
        disable :show_exceptions

        helpers do
          def unauthorized_template
            # Replace with path to your custom template
            @unauthenticated_template ||= File.read(File.join(File.dirname(__FILE__), "views", "401.html"))
          end
        end

        get '/unauthenticated' do
          status 403
          unauthorized_template
        end
      end
```

and

```ruby
class JekyllAuth
  class AuthSite < Sinatra::Base
    set :github_options, scopes: 'read:org', failure_app: MyBouncer
  end
end

**Comment by mebster** [comment]
@benbalter: great!  I was nearly there... thanks to you I am now :-)

**Comment by benbalter** [comment]
I'd also be glad to review a PR that gives preference to a `401.html` in the repo root if it exists. I think it'd be a nice feature to simplify this for other users.
