### ISSUE TITLE
Confused between jekyll and sinatra templating

### ISSUE THREAD

**Issue by mebster** [benbalter/jekyll-auth#94]
I'm trying to provide a bit of comfort to users, such that they know if they are authenticated or not.  I found this interesting example: https://github.com/atmos/sinatra-auth-github-test/blob/master/config.ru, but I'm confused between template formats and which processor processes what.

For example, how would I embed in my jekyll _includes templates if the user is authenticated.  Something like that:
```
<p>Message:</p>
<p>#{env['warden'].message}</p>

<h1>Simple App Example</h1>
<ul>
  <li><a href='/'>Home</a></li>
  <li><a href='/profile'>View profile</a><% if !env['warden'].authenticated? %> (implicit sign in)<% end %></li>
<% if authenticated? %>
  <li><a href='/logout'>Sign out</a></li>
<% else %>
  <li><a href='/login'>Sign in</a> (explicit sign in)</li>
<% end %>
</ul>
<hr />
```

**Comment by benbalter** [comment]
Jekyll is static, so it'd be hard to display different content for logged in and logged out users. You could, create a page entirely in Sinatra that would display the user's logged in/out status if you want.

**Comment by mebster** [comment]
Indeed.  Stupid question!
